Emsg v1 box Yospace messagedata parsing
bitmovin/bitmovin-player-web-integrations-yospace pull request #162
Opened 2022-10-11 06:16 UTC by saravanans-github

I've implemented the logic per Yospace's recommendation @ https://yospace.atlassian.net/servicedesk/customer/portal/8/YOSD-17476

kindly review and merge

2022-10-11 11:35 UTC, martinstark commented on src/ts/InternalBitmovinYospacePlayer.ts
> +      const yospaceMetadataObject = ID3Parser.ParseUint8Array(textEncoder.encode(metadata.messageData)) as any;
Just a thought, there is now a `parseId3Tags` method and a `ID3Parser` class being used that do quite different things. Maybe updating naming conventions would be an idea.

2022-10-12 04:02 UTC, saravanans-github commented on src/ts/InternalBitmovinYospacePlayer.ts
> +      const yospaceMetadataObject = ID3Parser.ParseUint8Array(textEncoder.encode(metadata.messageData)) as any;
@martinstark I've updated the naming convention to `YospaceID3Parser`. Not sure if that helps?

2022-10-12 14:50 UTC, dweinber requested changes

2022-10-12 14:50 UTC, dweinber commented on src/ts/InternalBitmovinYospacePlayer.ts
> +      const yospaceMetadataObject = YospaceEmsgToId3Parser.ParseUint8Array(
Variable shadowing isn't great (there's a variable in scope (line 916) that has the same naming). Please try to choose another name for this or the other variable.

2022-10-12 14:50 UTC, dweinber commented on src/ts/InternalBitmovinYospacePlayer.ts
> +        toMilliseconds(yospaceMetadataObject.startTime)
I don't think this works as expected. The `yospaceMetadataObject` you're accessing here is the one returned from `YospaceEmsgToId3Parser.ParseUint8Array` (L927), but that one only contains the 4-character frame names, but not `startTime`. The `startTime` is present in another `yospaceMetadataObject` (L917) but as you're shadowing this variable within this `if` block, I don't think you have actually access to that. Please see my suggestion above and rename one of the variables (or move the top one into the `else` part) and make sure the `startTime` is available.

2022-10-12 18:25 UTC, dweinber commented on src/ts/InternalBitmovinYospacePlayer.ts
> +        toMilliseconds(yospaceMetadataObject.startTime)
Confirmed in testing, `NaN` gets submitted to Yospace instead as the `startTime`. As Yospace expects a valid number, they're only checking for `< 0` to fail the validation, but it should also fail here.
Here's the log output of what our integration provides to the Yospace SDK in such an instance:
```
[20:22:12] [BitmovinYospacePlayer] - sending YSPlayerEvents.METADATA {"mediaId":"518145000","offset":0,"segmentCount":6,"segmentNumber":2,"playhead":null,"timestamp":1665598886093,"typeWithinSegment":{"key":"S","order":0}}
```
Note the `"playhead": null`.

2022-10-13 01:11 UTC, saravanans-github commented on src/js/YospaceEmsgToId3Parser.js
> + * Unauthorised copying of this file, via any medium is strictly prohibited.
Not sure; I've asked Yospace explicitly on the ticket.

2022-10-13 01:12 UTC, saravanans-github commented on tsconfig.json
> +    "allowJs": true
that's correct. I'm trying not to amend the Yospace file.

2022-10-13 06:03 UTC, saravanans-github commented on src/ts/InternalBitmovinYospacePlayer.ts
> +        toMilliseconds(yospaceMetadataObject.startTime)
@dweinber fixed per your comments. Logs look correct. 
```
[14:00:18] [BitmovinYospacePlayer] - sending YSPlayerEvents.METADATA {"mediaId":"518144996","offset":0,"segmentCount":4,"segmentNumber":1,"playhead":1665640789282.992,"timestamp":1665640818510,"typeWithinSegment":{"key":"S","order":0}}
```

2022-10-13 11:23 UTC, dweinber commented on src/ts/InternalBitmovinYospacePlayer.ts
> +    const startTime = metadata.presentationTime ? metadata.presentationTime : (this.player.getCurrentTime() as any);
1. Please remove the `as any`, shouldn't be necessary.
2. I just realized that the original code is actually buggy, because it doesn't do what you'd expect if `metadata.presentationTime` is `0`. Let's fix this right away please. The below suggestion should be safer to use, and is type safe because Typescript can now infere that `startTime` must be a `number`.

```suggestion
    const startTime = !isNaN(metadata.presentationTime) ? Number(metadata.presentationTime) : this.player.getCurrentTime();
```

2022-10-13 11:28 UTC, closed without merging