Queue timed metadata
bitmovin/bitmovin-player-web-integrations-yospace pull request #165
Opened 2023-03-29 12:13 UTC by martinstark

[Reference](https://eyevinn.slack.com/archives/C02QK0V2TLH/p1676543975850339)

There is some uncertainty around if `PlayerEvent.Metadata` is always triggered in correct sequential order by BM Player, since a customer and Yospace has reported TMD (TimedMetaData) being reported out of order under certain network conditions. See Yospace ticket linked in Reference above.

The BM Player should emit metadata events sequentially. According to @dweinber (see linked reference):

> Metadata is triggered [from BM Player] at the time the metadata should happen, as there's usually a time associated with each.

The current Yospace Integration listens to `PlayerEvent.Metadata` and pushes the metadata directly to the Yospace session, without doing any validation on the sequence or timing. To me, that makes it sound like the above quote isn't necessarily always true. The integration uses that event as the "source of truth" for metadata timing, and Yospace claims metadata is sometimes passed to the session out of order under severe network conditions.

This PR is primarily for debugging together with the customer. It creates a metadata cache by queuing events and not feeding them to the SDK until a playhead update occurs. The code keeps track of the largest playhead at which a TMD has been reported, if a TMD with a smaller playhead ever arrives it will log the message `MDD: BAD ORDER!`. That message indicates that the BM Player has given the Yospace Integration a metadata event that should have triggered before the previous metadata event.

2023-03-31 08:21 UTC, dweinber requested changes

2023-03-31 08:21 UTC, dweinber commented on src/ts/InternalBitmovinYospacePlayer.ts
> +          console.log(
Please use the `Logger` object instead of `console` directly.

Also, what does `MDD:` stand for?

2023-03-31 08:21 UTC, dweinber commented on src/ts/InternalBitmovinYospacePlayer.ts
> +            console.log('MDD: reported item', item.getPlayhead(), item);
Please use the `Logger` object instead of `console` directly.

2023-03-31 08:21 UTC, dweinber commented on src/ts/InternalBitmovinYospacePlayer.ts
> +              console.log('MDD: BAD ORDER!');
Please use the `Logger` object instead of `console` directly.

2023-03-31 08:21 UTC, dweinber commented on src/ts/InternalBitmovinYospacePlayer.ts
> +    console.log('MDD: queued', yospaceMetadataObject.getPlayhead(), yospaceMetadataObject);
Please use the `Logger` object instead of `console` directly.

2023-03-31 08:21 UTC, dweinber commented on src/ts/InternalBitmovinYospacePlayer.ts
> +    this.metadataQueue.push(yospaceMetadataObject);
The only concern here is that `DATERANGE` metadata gets through the check in L1254 above, but we don't have a method that creates the `yospaceMetadataObject` out of the `DATERANGE` information, which means we could push `undefined` to the `metadataQueue`. I don't think that's expected, due to that, the log message in the next line leads to trying to access `getPlayhead()` on `undefined`.

Do we need to add a `DATERANGE`->`yospaceMetadataObject` conversion or should we also remove `DATERANGE` from the valid types?

2023-07-07 14:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitmovin/bitmovin-player-web-integrations-yospace?pullRequest=165) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitmovin/bitmovin-player-web-integrations-yospace?pullRequest=165) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitmovin/bitmovin-player-web-integrations-yospace?pullRequest=165) it.</sub>

2024-03-08 14:09 UTC, martinstark commented
I'll close this PR for now, let me know if we should pick this back up.

2024-03-08 14:09 UTC, closed without merging