Extend API
bitmovin/bitmovin-player-web-integrations-yospace pull request #170
Opened 2024-03-08 13:30 UTC by martinstark

This PR builds on the fixes in https://github.com/bitmovin/bitmovin-player-web-integrations-yospace/pull/169. When it is merged, this PR should be redirected to the `develop` branch. 

Adds the following:

- Ability to fetch the full duration of an ongoing ad break. This duration can be used to display a count down timer for the full duration of an ad break
- Ability to fetch the current timestamp including stitched ad durations when viewing VODs. CAUTION: this timestamp may refer to different relative positions on each video start, depending on length of stitched ads
- Ability to fetch the duration of a VOD including stitched ad duration. CAUTION: this number may be different on every video start, depending on length of stitched ads
- Extend `TimeChangedEvent` to include `timeWithAds` in addition to the regular `time`

2024-03-13 07:57 UTC, dweinber requested changes
Thanks for the contribution. A few comments to address, and please add a CHANGELOG.md entry - thanks!

2024-03-13 07:57 UTC, dweinber commented on src/ts/BitmovinYospacePlayerAPI.ts
> +  getCurrentAdBreakDuration(): number;
Feels like this API isn't necessary as the data is already exposed.`player.ads.getActiveAdBreak()?.duration ?? 0` should be equivalent, or am I missing something?

2024-03-13 07:57 UTC, dweinber commented on src/ts/BitmovinYospacePlayerAPI.ts
> +  getDurationWithAds(): number;
I'm inclined to suggest using an optional parameter for the existing `getDuration` API, like `getDuration(withAds = false)`. Thoughts?

2024-03-13 07:57 UTC, dweinber commented on src/ts/BitmovinYospacePlayerAPI.ts
> +  getCurrentTimeWithAds(): number;
I'm inclined to suggest using an optional parameter for the existing `getCurrentTime` API, like `getCurrentTime(withAds = false)`. Thoughts?

2024-03-14 10:12 UTC, martinstark commented on src/ts/BitmovinYospacePlayerAPI.ts
> +  getCurrentAdBreakDuration(): number;
an explicit method was requested (cc @saravanans-github), I'm happy to remove it if the existing API fulfils the need

2024-03-14 10:14 UTC, martinstark commented on src/ts/BitmovinYospacePlayerAPI.ts
> +  getDurationWithAds(): number;
in slack discussions we opted for explicit methods, but I have no strong feeling here (cc @saravanans-github)

2024-03-14 10:14 UTC, martinstark commented on src/ts/BitmovinYospacePlayerAPI.ts
> +  getCurrentTimeWithAds(): number;
in slack discussions we opted for explicit methods, but I have no strong feeling here (cc @saravanans-github)

2024-03-14 10:29 UTC, martinstark commented
@dweinber changelog is included in #171 , if that is okay. It could be merged into this branch before merging to develop

2024-03-18 14:53 UTC, dweinber commented
Thanks @martinstark, I've started a conversation around existing vs new APIs separately.

Re: Changelog:
I believe what's done in this PR should also be listed by this PR 🙂 (i.e. just the addition of the new APIs should be listed as part of this PR)

2024-03-18 15:10 UTC, martinstark commented
> Re: Changelog:
> I believe what's done in this PR should also be listed by this PR 🙂 (i.e. just the addition of the new APIs should be listed as part of this PR)

Sure! Since the PRs are built on top of each other I'll have a small rebase/force-push party to get it sorted once we agree to the finalized API. I'll move the changelog to the appropriate PR when that happens.

2024-03-18 15:17 UTC, dweinber commented
Ah ok, missed that. I thought we'd merge this one, and then 171 would be just done against `develop` as well. 

All good then, don't worry about the changelog.

2024-03-18 15:26 UTC, martinstark commented
Since I'll likely need to make changes here I'll be doing the rebasing regardless, so I can make sure the changelog is in the correct place as part of that

2024-03-21 11:03 UTC, martinstark commented
@dweinber updated the PR

2024-03-21 12:50 UTC, dweinber approved these changes
Code looks good, thanks for the updates!

2024-03-21 12:50 UTC, dweinber commented on CHANGELOG.md
> +- added mode argument to getDuration to enable fetching absolute duration
```suggestion
- `mode` argument to `getDuration` to enable fetching absolute duration including ad durations
```

2024-03-21 13:09 UTC, merged