Ad Holiday Feature
bitmovin/bitmovin-player-web-integrations-yospace pull request #171
Opened 2024-03-14 09:52 UTC by martinstark

## Description
By providing an ad immunity configuration after initialization, a user that has watched an ad break will become immune to ad breaks for a period. Any ad break position passed during the immunity period is permanently disabled, so that it is not possible to enter the break at a later point after the immunity has expired. See changelog for more detailed description of new API methods.

## Checklist (for PR submitter and reviewers)
- [ ] `CHANGELOG` entry

2024-03-21 13:07 UTC, dweinber requested changes

2024-03-21 13:07 UTC, dweinber commented on src/ts/InternalBitmovinYospacePlayer.ts
> +        this.player.seek(toSeconds(upcomingAdBreak.getStart() + upcomingAdBreak.getDuration()));
So we are skipping (up to) half a second of the main content before each deactivated ad break. Just wanted to point this out @saravanans-github, is this okay?

2024-03-21 13:07 UTC, dweinber commented on src/ts/InternalBitmovinYospacePlayer.ts
> +        this.player.seek(toSeconds(upcomingAdBreak.getStart() + upcomingAdBreak.getDuration()));
So we are skipping (up to) half a second of the main content before each ad break we're deactivating due to ad immunity. Just wanted to point this out @saravanans-github, is this okay?

2024-03-21 13:23 UTC, martinstark commented on src/ts/BitmovinYospacePlayerAPI.ts
> +  active: boolean;
Yospace has an internal concept of an ad break being active or not. An inactive ad break will not trigger any ad events (no ad start, ad end, quartile, or other impression, adbreak start and end are still raised). It is then up to the integration how to handle an inactive break (e.g. seek past it).

This boolean is what is being surfaced here, in order to give Policies access to this property. Currently, the only way for a break to become inactive is if its boundary is crossed during an immunity period.

In integrations I've worked on in the past, any viewed ad break would normally be marked as inactive, and the integration would skip (seek) past them if `currentTime` were move into an already viewed the ad break boundary a second time.

2024-03-21 13:25 UTC, dweinber commented on src/ts/BitmovinYospacePlayerAPI.ts
> +  active: boolean;
Makes sense! And we might change the behavior for watched ads like you described in the future, let's see 👍

2024-03-21 13:28 UTC, martinstark commented on src/ts/InternalBitmovinYospacePlayer.ts
> +    const adBreakCheckOffset = 500;
This number is probably going away based on discussion on Slack. It's almost impossible to prevent a few ad frames from showing before a seek has time to propagate, since it's device performance dependent.

The current theory is that preventing ad frames from showing up before the seek has time to trigger can be done by pausing the video before initiating the seek, but that has it's own drawbacks (the video is paused (appears to freeze) while waiting for seek to finish)

2024-03-21 13:29 UTC, martinstark commented on src/ts/InternalBitmovinYospacePlayer.ts
> +        this.player.seek(toSeconds(upcomingAdBreak.getStart() + upcomingAdBreak.getDuration()));
see above comment, this behaviour is probably changing

2024-03-21 13:29 UTC, martinstark commented on src/ts/InternalBitmovinYospacePlayer.ts
> +        this.player.seek(toSeconds(upcomingAdBreak.getStart() + upcomingAdBreak.getDuration()));
see above comment, this behaviour is probably changing

2024-03-21 13:29 UTC, dweinber commented on src/ts/InternalBitmovinYospacePlayer.ts
> +    const adBreakCheckOffset = 500;
I'm aware of that, but I think you'll still need to look a bit ahead to mark upcoming ad breaks as inactive, or not? IMO that's what the offset will still be needed for. But let's see once the implementation was changed.

2024-03-21 14:02 UTC, martinstark commented on src/ts/InternalBitmovinYospacePlayer.ts
> +        if (breakStart > currentTime && breakStart < time) {
It's an interesting edge case, I'll implement your suggestion, but since this logic only triggers during ad immunity, the timestamp that the user would land on would immediately trigger another seek past the break

2024-03-21 14:35 UTC, martinstark commented on src/ts/BitmovinYospacePlayerAPI.ts
> +   * postrolls are excluded from ad immunity
fixed in new git tree

2024-03-21 14:36 UTC, martinstark commented on src/ts/BitmovinYospacePlayerAPI.ts
> +   * duration 0 disables the feature
removed in new git tree

2024-03-21 14:36 UTC, martinstark commented on src/ts/BitmovinYospacePlayerAPI.ts
> +   * duration 0 means the feature is disabled
removed in new git tree

2024-03-21 14:36 UTC, martinstark commented on src/ts/BitmovinYospacePlayerAPI.ts
> +}
docs added in new git tree

2024-03-21 14:36 UTC, martinstark commented on src/ts/InternalBitmovinYospacePlayer.ts
> +        if (breakStart > currentTime && breakStart < time) {
changed in new git tree

2024-03-21 14:37 UTC, martinstark commented on src/ts/InternalBitmovinYospacePlayer.ts
> +    const adBreakCheckOffset = 500;
it's now configurable

2024-03-25 12:18 UTC, dweinber requested changes

2024-03-25 12:18 UTC, dweinber commented on src/ts/InternalBitmovinYospacePlayer.ts
> +    );
Looks like these event suppressings are re-added everytime a `performBreakSkip` happens, but I don't see that these events get removed again from the break, or maybe I've missed it.
That would mean that after the first time `performBreakSkip` was called, the player would not emit any paused/seek/seeked events anymore.

2024-03-25 13:26 UTC, martinstark commented on src/ts/InternalBitmovinYospacePlayer.ts
> +          .filter((adBreak: YospaceAdBreak) => adBreak.duration > 0)
I think you mean `adBreak.active || adBreak.duration > 0`?

2024-03-25 13:29 UTC, martinstark commented on src/ts/InternalBitmovinYospacePlayer.ts
> +    this.endAdImmunityPeriod();
The question on (L953+954) relates to resetting the config, not the immunity state. E.g. re-set the configured duration to 0 on each video start.

I'm pretty sure that's not desired, but thought that it's worth to pose the question

2024-03-25 13:42 UTC, martinstark commented on src/ts/InternalBitmovinYospacePlayer.ts
> +    );
I see, I thought these were one-off suppression events, I based it off of the logic I found here, which also doesn't seem to remove the suppressed events: https://github.com/bitmovin/bitmovin-player-web-integrations-yospace/blob/2de540a209288737cb8b2ab1fb162ede6ef9e9ed/src/ts/InternalBitmovinYospacePlayer.ts#L1137-L1159

but I see now that this logic is for the post-roll, it finishes playback right away, and presumably clears suppressed events the next time a video is loaded.

In theory I could use this same logic to enable post-roll ad immunity, e.g. instead of trying to seek past the post-roll, just end playback when the postroll is detected.

2024-03-25 14:02 UTC, dweinber commented on src/ts/InternalBitmovinYospacePlayer.ts
> +    this.endAdImmunityPeriod();
Understood, thanks for clarifying.

2024-03-25 18:51 UTC, martinstark commented on src/ts/InternalBitmovinYospacePlayer.ts
> +          .filter((adBreak: YospaceAdBreak) => adBreak.duration > 0)
on the final example you have 5
`data.filter(adbreak => adbreak.active || adbreak.duration > 5)`
I think it should work with 9
`data.filter(adbreak => adbreak.active || adbreak.duration > 0)`

2024-03-26 08:20 UTC, dweinber commented on src/ts/InternalBitmovinYospacePlayer.ts
> +          .filter((adBreak: YospaceAdBreak) => adBreak.duration > 0)
How did that happen? 😄 😅 🙈 Too little caffeine maybe. 

This time I'll try to get it right:
```
data.filter(adbreak => adbreak.active).filter(adbreak => adbreak.duration > 0)
[
  {
    "active": true,
    "duration": 5
  }
]

data.filter(adbreak => adbreak.active && adbreak.duration > 0)
[
  {
    "active": true,
    "duration": 5
  }
]

data.filter(adbreak => adbreak.active || adbreak.duration > 0)
[
  {
    "active": true,
    "duration": 5
  },
  {
    "active": true,
    "duration": 0
  },
  {
    "active": false,
    "duration": 5
  }
]
```

So I think `adbreak.active && adbreak.duration > 0` is correct in this case

2024-03-26 09:16 UTC, martinstark commented on src/ts/InternalBitmovinYospacePlayer.ts
> +          .filter((adBreak: YospaceAdBreak) => adBreak.duration > 0)
:+1: yeah, of course it should be `&&`, I'm apparently also too low on caffeine :joy:

2024-04-19 12:07 UTC, martinstark commented on src/ts/BitmovinYospacePlayerAPI.ts
> + * to skip past, in order to mitigate ad frames being displayed before they have time to be seeked past.
updated to seconds

2024-04-19 12:09 UTC, martinstark commented on src/ts/InternalBitmovinYospacePlayer.ts
> +    );
removed suppression, it seems to have caused a bug with the holiday logic as well

2024-04-23 14:53 UTC, dweinber commented on src/ts/InternalBitmovinYospacePlayer.ts
> +    // would require configuration for each new video start
@saravanans-github can you please comment on the expected behavior here?

2024-04-23 15:13 UTC, dweinber reviewed
Code looks good 👍 

Would be good to get @saravanans-github's feedback on the open question.

2024-04-23 15:13 UTC, dweinber commented on src/ts/InternalBitmovinYospacePlayer.ts
> +      typeof this.adImmunityConfig.adBreakCheckOffset === 'number' ? this.adImmunityConfig.adBreakCheckOffset : 0.3;
Would be nice to have a default value in a variable somewhere at the top of the class or file instead of the magic number here.

2024-05-16 09:10 UTC, martinstark commented on src/ts/InternalBitmovinYospacePlayer.ts
> +      typeof this.adImmunityConfig.adBreakCheckOffset === 'number' ? this.adImmunityConfig.adBreakCheckOffset : 0.3;
Fixed :+1:

2024-05-16 11:35 UTC, dweinber commented on src/ts/InternalBitmovinYospacePlayer.ts
> +    );
So just to be clear, now when skipping an ad break, the player would trigger `Pause`, `Seek`, `Seeked`, `Play`, `Playing` events?

2024-05-16 13:47 UTC, martinstark commented on src/ts/InternalBitmovinYospacePlayer.ts
> +    );
Yes. If this is not desired I'll probably need some guidance on how to correctly suppress and unsuppress events for the skip. 

With suppression on during the skip I can see edge cases like the user interacting with the player controls while the suppression is still active, before the skip seek has had time to finish. Since the break never activates, the player controls are still usable during the duration of the skip.

I think the skip would need to do something like `disable UI interaction -> suppress events -> perform skip -> unsuppress events -> enable UI interaction` for it to avoid weird corner case states.

2024-05-16 13:55 UTC, martinstark commented on src/ts/InternalBitmovinYospacePlayer.ts
> +    // would require configuration for each new video start
Since the customer has not commented during their testing, I feel fairly certain it's working as expected

2024-05-16 13:57 UTC, dweinber commented on src/ts/InternalBitmovinYospacePlayer.ts
> +    // would require configuration for each new video start
Sounds fair 👍

2024-06-18 07:41 UTC, dweinber commented on CHANGELOG.md
> +
These lines should be removed. This is all still `Unreleased` and will end up in 2.4.0.
```suggestion
```

2024-06-18 08:43 UTC, martinstark commented on CHANGELOG.md
> +
Fixed

2024-06-18 08:51 UTC, dweinber approved these changes
All good from my side, waiting for @saravanans-github and the customer to confirm test results

2024-07-10 14:40 UTC, merged